
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.11.0-1027-oem - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CheckCSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/usr/share/cmake-3.28/Modules/FindThreads.cmake:97 (CHECK_C_SOURCE_COMPILES)"
      - "/usr/share/cmake-3.28/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "/usr/share/cmake-3.28/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "deps/vera/cmake/FindFFMPEG.cmake:34 (find_dependency)"
      - "deps/vera/src/CMakeLists.txt:148 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "/home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr"
      binary: "/home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/home/patricio/Desktop/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/patricio/Desktop/emsdk/upstream/emscripten/cmake/Modules;/home/patricio/Desktop/emsdk/upstream/emscripten/cmake/Modules;/home/patricio/Desktop/emsdk/upstream/emscripten/cmake/Modules;/home/patricio/Desktop/emsdk/upstream/emscripten/cmake/Modules;/home/patricio/Desktop/emsdk/upstream/emscripten/cmake/Modules;/home/patricio/Desktop/vera_gsplat/deps/vera/cmake/"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_48f67/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_48f67.dir/build.make CMakeFiles/cmTC_48f67.dir/build
        gmake[1]: Entering directory '/home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr'
        Building C object CMakeFiles/cmTC_48f67.dir/src.c.o
        /home/patricio/Desktop/emsdk/upstream/emscripten/emcc -DCMAKE_HAVE_LIBC_PTHREAD   -MD -MT CMakeFiles/cmTC_48f67.dir/src.c.o -MF CMakeFiles/cmTC_48f67.dir/src.c.o.d -o CMakeFiles/cmTC_48f67.dir/src.c.o -c /home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr/src.c
        Linking C executable cmTC_48f67.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_48f67.dir/link.txt --verbose=1
        /home/patricio/Desktop/emsdk/upstream/emscripten/emcc @CMakeFiles/cmTC_48f67.dir/objects1.rsp -o cmTC_48f67.js 
        clang: warning: future releases of the clang compiler will prefer GCC installations containing libstdc++ include directories; '/usr/lib/gcc/x86_64-linux-gnu/13' would be chosen over '/usr/lib/gcc/x86_64-linux-gnu/14' [-Wgcc-install-dir-libstdcxx]
        gmake[1]: Leaving directory '/home/patricio/Desktop/vera_gsplat/docs/CMakeFiles/CMakeScratch/TryCompile-HT2kmr'
        
      exitCode: 0
...
